_target_: torch.utils.data.DataLoader

dataset:
  _target_: src.datamodule.PubLayNet.PubLayNet
  data_path: ./datasets/publaynet
  num_cat: 6
  lex_order: False
  permute_elements: False

batch_size: 512
num_workers: 12
pin_memory: True
persistent_workers: True
shuffle: True
drop_last: False
collate_fn:
  _target_: src.datamodule.PubLayNet.collate_fn
  _partial_: true
  max_len: ${data.max_len}
  format: ${data.format}